
build:
	rm -rf src/github.com
	go get github.com/gorilla/mux
	go get github.com/unrolled/render
	go get go.mongodb.org/mongo-driver/bson
	go get go.mongodb.org/mongo-driver/mongo
	go get go.mongodb.org/mongo-driver/mongo/options
	go get github.com/go-redis/redis
	go build -o main .
